version: '3'

services:
  ci-build:
    image: microsoft/aspnetcore-build-nightly:2.0
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./bidsquid.sln && dotnet publish ./bidsquid.sln -c Release -o ./obj/Docker/publish"
